### ISSUE TITLE
好用，跳过极其方便，就是有次我发现视频中间插入的广告没跳过，之后能否完善一下。

### ISSUE THREAD

**Issue by xiaosaaaa** [JoeyGambler/youtube-ad-skip#1]
如题，不知道我遇到的是不是个例，麻烦您了。

**Comment by JoeyGambler** [comment]
我知道这个问题，但是很抱歉，我目前解决不了。

**Comment by JoeyGambler** [comment]
> 如题，不知道我遇到的是不是个例，麻烦您了。

我知道这个问题，但是很抱歉，我目前解决不了。

**Comment by xiaosaaaa** [comment]
> > 如题，不知道我遇到的是不是个例，麻烦您了。
> 
> 我知道这个问题，但是很抱歉，我目前解决不了。

其实影响不大，瑕不掩瑜。
